import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import "./styles/globals.css";
import Provider from "./_trpc/Provider";

const space = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-space",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${space.variable} antialiased`}
      >
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
